language: python
python:
  - "2.7"
  - "3.3"
git:
  submodules: false
sudo: false  # Enables running on faster infrastructure.
install:
  - pip install -r dev-requirements.txt
  - pip install coveralls
  - pip install pep8
script:
  - ./checkstyle.sh
  - coverage run --source willie -m py.test .
  - coverage report --show-missing
